name: "Build FtcRobotController APK"
on:
  workflow_dispatch:
  push:
    tags:
      -'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build-apk:
    name: "Build FtcRobotController APK"
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
    - name: Compile TeamCode
      run: ./gradlew assembleRelease
    - name: Upload robot controller APK
      uses: actions/upload-artifact@v4
      with:
        name: FtcRobotController-FtcDashboard-${{github.ref_name}}.apk
        path: TeamCode/build/outputs/apk/release/TeamCode-release.apk
