name: "Build OnBot Resources"
on:
  push:
  pull_request:

jobs:
  build-apk:
    name: "Build FtcRobotController APK and AAR"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
    - name: Compile TeamCode and Dashboard AAR
      run: ./gradlew assembleRelease
    - name: Finalize FTC Dashboard AAR
      run: mkdir -p output && cp FtcDashboard/build/outputs/aar/FtcDashboard-release.aar output/FtcDashboard-${{github.ref_name}}.aar
    - name: Finalize robot controller APK
      run: cp TeamCode/build/outputs/apk/release/TeamCode-release.apk output/FtcRobotController-FtcDashboard-${{github.ref_name}}.apk
    - name: Upload assets
      uses: actions/upload-artifact@v4
      with:
        name: FtcDashboard-${{github.ref_name}}
        path: output
